import React, { useState } from 'react';
import {
  X,
  Clock,
  Users,
  Utensils,
  CheckCircle2,
  AlertCircle,
  Copy,
  Check,
  Heart,
  Sparkles,
  Lightbulb,
  ArrowRightLeft
} from 'lucide-react';

export default function RecipeDetails({
  recipe,
  onClose,
  isSaved,
  onToggleSave,
  onGenerateAgain
}) {
  const [copied, setCopied] = useState(false);

  if (!recipe) return null;

  const isVeg = recipe.diet?.toLowerCase().includes('veg');

  const handleCopyRecipe = () => {
    const formattedText = `
🍳 ${recipe.name.toUpperCase()}
${recipe.description}

⏱️ Cooking Time: ${recipe.cooking_time_minutes} minutes
👥 Servings: ${recipe.servings}
🌍 Cuisine: ${recipe.cuisine} | Diet: ${recipe.diet} | Difficulty: ${recipe.difficulty}

--- INGREDIENTS ---
${recipe.ingredients?.map(ing => `• ${ing.name}: ${ing.quantity}`).join('\n') || 'N/A'}

--- MISSING / PANTRY ITEMS NEEDED ---
${recipe.missing_ingredients?.map(m => `• ${m}`).join('\n') || 'None'}

--- STEP-BY-STEP INSTRUCTIONS ---
${recipe.steps?.map((step, idx) => `${idx + 1}. ${step}`).join('\n\n')}

--- SMART SUBSTITUTIONS ---
${recipe.substitutions?.map(s => `• ${s.original} ➔ ${s.replacement}`).join('\n') || 'None'}

--- CHEF TIPS ---
${recipe.tips?.map(t => `💡 ${t}`).join('\n') || 'None'}

Generated by RecipeGen AI
    `.trim();

    navigator.clipboard.writeText(formattedText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="modal-overlay" onClick={onClose} role="dialog" aria-modal="true">
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        {/* Modal Header */}
        <div className="modal-header">
          <div>
            <div className="badge-group" style={{ marginBottom: '0.5rem' }}>
              <span className={`badge ${isVeg ? 'badge-veg' : 'badge-nonveg'}`}>
                {recipe.diet || 'Any'}
              </span>
              <span className="badge badge-cuisine">
                {recipe.cuisine}
              </span>
              <span className="badge badge-difficulty">
                {recipe.difficulty}
              </span>
            </div>
            <h2 style={{ fontSize: '1.75rem', lineHeight: 1.25 }}>{recipe.name}</h2>
          </div>
          <button
            type="button"
            className="modal-close-btn"
            onClick={onClose}
            aria-label="Close modal"
          >
            <X size={20} />
          </button>
        </div>

        {/* Modal Body */}
        <div className="modal-body">
          <p style={{ color: 'var(--text-secondary)', fontSize: '1.05rem', marginBottom: '1.5rem', lineHeight: 1.6 }}>
            {recipe.description}
          </p>

          {/* Cooking Info Stats */}
          <div className="meta-stats" style={{ marginBottom: '2rem' }}>
            <div className="stat-item">
              <Clock size={18} />
              <span style={{ fontSize: '0.95rem' }}><strong>Time:</strong> {recipe.cooking_time_minutes} minutes</span>
            </div>
            <div className="stat-item">
              <Users size={18} />
              <span style={{ fontSize: '0.95rem' }}><strong>Yield:</strong> {recipe.servings} Servings</span>
            </div>
            <div className="stat-item">
              <Utensils size={18} />
              <span style={{ fontSize: '0.95rem' }}><strong>Difficulty:</strong> {recipe.difficulty}</span>
            </div>
          </div>

          {/* Ingredients Section */}
          <div className="detail-section">
            <h3 className="detail-section-title">
              <Utensils size={18} />
              Ingredients & Quantities
            </h3>
            <div className="ingredients-detail-grid">
              {recipe.ingredients?.map((ing, idx) => (
                <div key={idx} className="ingredient-detail-item">
                  <span className="ingredient-detail-name">{ing.name}</span>
                  <span className="ingredient-detail-qty">{ing.quantity}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Missing Ingredients Highlight */}
          {recipe.missing_ingredients && recipe.missing_ingredients.length > 0 && (
            <div className="detail-section">
              <h3 className="detail-section-title" style={{ color: 'var(--accent-amber)' }}>
                <AlertCircle size={18} />
                Pantry Staples Needed (Not in your initial list)
              </h3>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
                {recipe.missing_ingredients.map((item, idx) => (
                  <span
                    key={idx}
                    style={{
                      background: 'rgba(245, 158, 11, 0.12)',
                      border: '1px solid rgba(245, 158, 11, 0.3)',
                      color: 'var(--accent-amber)',
                      padding: '0.4rem 0.8rem',
                      borderRadius: 'var(--radius-sm)',
                      fontSize: '0.85rem'
                    }}
                  >
                    + {item}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Step-by-Step Instructions */}
          <div className="detail-section">
            <h3 className="detail-section-title">
              <Sparkles size={18} />
              Step-by-Step Cooking Instructions
            </h3>
            <div className="steps-list">
              {recipe.steps?.map((step, idx) => (
                <div key={idx} className="step-card">
                  <div className="step-number">{idx + 1}</div>
                  <div className="step-text">{step}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Substitutions */}
          {recipe.substitutions && recipe.substitutions.length > 0 && (
            <div className="detail-section">
              <h3 className="detail-section-title">
                <ArrowRightLeft size={18} />
                Smart Substitutions
              </h3>
              {recipe.substitutions.map((sub, idx) => (
                <div key={idx} className="info-card-box">
                  <strong>Replace {sub.original}:</strong> Use <em>{sub.replacement}</em> instead if not available.
                </div>
              ))}
            </div>
          )}

          {/* Cooking Tips */}
          {recipe.tips && recipe.tips.length > 0 && (
            <div className="detail-section">
              <h3 className="detail-section-title">
                <Lightbulb size={18} />
                Pro Cooking Tips
              </h3>
              {recipe.tips.map((tip, idx) => (
                <div key={idx} className="info-card-box" style={{ borderLeftColor: 'var(--accent-green)' }}>
                  {tip}
                </div>
              ))}
            </div>
          )}

          {/* Modal Actions */}
          <div className="modal-actions">
            <button
              type="button"
              className="btn-modal-action btn-modal-primary"
              onClick={() => onToggleSave(recipe)}
            >
              <Heart size={16} fill={isSaved ? 'white' : 'none'} />
              {isSaved ? 'Saved to Favorites' : 'Save Recipe'}
            </button>

            <button
              type="button"
              className="btn-modal-action btn-modal-secondary"
              onClick={handleCopyRecipe}
            >
              {copied ? <Check size={16} style={{ color: '#34d399' }} /> : <Copy size={16} />}
              {copied ? 'Copied to Clipboard!' : 'Copy Recipe'}
            </button>

            <button
              type="button"
              className="btn-modal-action btn-modal-secondary"
              onClick={() => {
                onClose();
                onGenerateAgain();
              }}
            >
              <Sparkles size={16} />
              Generate Again
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
